### PR TITLE
Move group launch information out to a form

### PR DESCRIPTION
**Pull request by kimdhamilton**
To avoid duplication, moving the required information out to a group launch form, which chair or proposer will fill out

### CODE REVIEW

**Review by ankurdotb — COMMENTED** [review]
Should we use a Google Form rather than a form in a doc?

**Comment by kimdhamilton** [comment]
> Should we use a Google Form rather than a form in a doc?

I thought about this, but it's not clear that google form can keep state for editing/revising.

**Review by ankurdotb — APPROVED** [review]

**Comment by ankurdotb** [comment]
> I thought about this, but it's not clear that google form can keep state for editing/revising.

Yes, it does but [only if they are logged into/have a Google Account](https://support.google.com/docs/answer/10952360?hl=en) (which may not be the case for everyone, especially if company emails are Microsoft only). Also can't be filled in collaboratively by multiple people, and _will_ get purged after 30 days even if auto-saved. So, I've kinda changed my mind on this after looking closer at the topic (hence the approval). I don't have rights to merge though.

**Comment by kimdhamilton** [comment]
> > I thought about this, but it's not clear that google form can keep state for editing/revising.
> 
> Yes, it does but [only if they are logged into/have a Google Account](https://support.google.com/docs/answer/10952360?hl=en) (which may not be the case for everyone, especially if company emails are Microsoft only). Also can't be filled in collaboratively by multiple people, and _will_ get purged after 30 days even if auto-saved. So, I've kinda changed my mind on this after looking closer at the topic (hence the approval). I don't have rights to merge though.

I merged, but we'll also give you permission

**Pull request merged**
