### PR TITLE
Add TSC notification step to SC approval stage

### PR DESCRIPTION
**Pull request by bumblefudge**
Will leave open until next SC meeting to discuss/consider.  Backstory: DIDComm WG was asking about this section of the Governance Operating Addendum:

image

### CODE REVIEW

**Review by brentzundel — APPROVED** [review]

**Comment by andorsk** [comment]
Can we merge this. This is good. Thank you @bumblefudge

**Comment by peacekeeper** [comment]
Yes let's merge, go ahead..

**Comment by bumblefudge** [comment]
just one more week! (kidding!)

**Comment by kimdhamilton** [comment]
@andorsk @andorsk this PR still looks valid. Ok to merge?

**Comment by andorsk** [comment]
Yes. Let's merge

**Pull request merged**
