### PR TITLE
to add IETF section and links

### PR DESCRIPTION
**Pull request by bumblefudge**
to the spec tooling page, that is

### CODE REVIEW

**Review by peacekeeper — APPROVED** [review]
Looks good, this will be useful guidance for new work items.

**Comment by nembal** [comment]
shooting an email to TSC.

**Comment by dwaite** [comment]
Note `markdown2rfc` is a docker container for running the python `xml2rfc` and the go `mmark` tools (so you don't need python/go toolchains installed to the host)

**Comment by bumblefudge** [comment]
Ship it barring objections from TSC, @nembal ?

**Review by csuwildcat — APPROVED** [review]

**Review by kdenhartog-mattr — APPROVED** [review]

**Comment by bumblefudge** [comment]
thanks for the review, y'all!

**Pull request merged**
